
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-casts: true
  plugins:
    - custom_lint

custom_lint:
  rules:
    - enable_all_lint_rules
#    - missing_provider_scope
#    - provider_paramteers
#    - avoid_public_notifier_properties


linter:
  rules:
    - prefer_relative_imports
    - require_trailing_commas
    - avoid_empty_else
    - prefer_final_fields
    - prefer_single_quotes
    - avoid_init_to_null
    - avoid_web_libraries_in_flutter
    - avoid_unnecessary_containers
    - no_logic_in_create_state
    - avoid_print