name: happy_aging_admin
description: admin web page
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3


  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.3.1
  logger: ^2.0.1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1 #retrofit


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # retrofit
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
    - family: Pyeongchangpeace
      fonts:
        - asset: assets/fonts/pyeongchangpeace_light.otf
          weight: 500
        - asset: assets/fonts/pyeongchangpeace_bold.otf
          weight: 700